version: "3"

services:
  backend1:
    build: ./backend
    environment:
      - INSTANCE_NAME=backend1

  backend2:
    build: ./backend
    environment:
      - INSTANCE_NAME=backend2

  backend3:
    build: ./backend
    environment:
      - INSTANCE_NAME=backend3

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend1
      - backend2
      - backend3

  redis:
    image: redis:latest

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"