events {}

http {
    upstream backend {
        server backend1:3000;
        server backend2:3000;
        server backend3:3000;
    }

    server {
        listen 80;

        # ✅ 1. ALL API ROUTES
        location /api/ {
            proxy_pass http://backend;
        }

        # ✅ 2. Short URL Redirect
        location ~ ^/[a-zA-Z0-9_-]+$ {
            proxy_pass http://backend;
        }

        # ✅ 3. React Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }
    }
}